# Generated by Django 3.2 on 2021-04-26 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarthquakeXLSX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now=True, verbose_name='Created Date')),
                ('xlsx_file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])], verbose_name='XLSX File')),
                ('updated_date', models.DateField(auto_now_add=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Earthquake XLSX',
                'verbose_name_plural': 'Earthquake XLSXs',
            },
        ),
    ]
